import 'mock_firebase.dart';

class Translator {
  static final Map<String, Map<String, String>> _dictionary = {
    'English': {
      'about': 'About',
      'about_desc': 'Kouture is the ultimate destination for high-end African fashion. We connect the best artisans and designers with a global audience, with an emphasis on quality and tailor-made.',
      'about_kouture': 'About Kouture',
      'accessoires': 'Accessories',
      'accessories': 'Accessories',
      'account': 'Account',
      'account_created': 'Account Created!',
      'activities': 'Activities',
      'add_address_desc': 'Add an address to make checkout easier.',
      'add_new_address': 'ADD NEW ADDRESS',
      'add_payment_method': 'Add a payment method',
      'add_photo': 'Add Photo',
      'add_review': 'Add Review',
      'add_to_cart': 'Add to Cart',
      'added_to_cart': 'Added to cart!',
      'address_added_success': 'Address added successfully',
      'address_type': 'Address Type',
      'agree_terms': 'I agree to the Terms & Conditions',
      'all': 'All',
      'all_currencies': 'All currencies',
      'already_have_account': 'Already have an account?',
      'ankle': 'Ankle',
      'apply_filters': 'Apply Filters',
      'arm_length': 'Arm Length',
      'articles': 'article(s)',
      'at': 'at',
      'back': 'BACK',
      'bank_card': 'Bank Card',
      'bank_card_title': 'Bank Card',
      'biceps': 'Biceps',
      'birth_date': 'Birth Date',
      'bust_chest': 'Bust/Chest',
      'buy_now': 'Buy Now',
      'calf': 'Calf',
      'cancel': 'Cancel',
      'cancel_return_home': 'CANCEL AND RETURN HOME',
      'card_name': 'Name on card',
      'card_number': 'Card number',
      'cardholder': 'CARDHOLDER',
      'cart': 'My Cart',
      'cart_empty': 'Your cart is empty',
      'categories': 'Categories',
      'categories_title': 'Categories',
      'chaussures': 'Shoes',
      'checkout': 'Go to Checkout',
      'checkout_confirmation': 'Checkout Confirmation',
      'city': 'City',
      'city_hint': 'e.g. Yaoundé',
      'clear_all': 'Clear All',
      'colors': 'Colors',
      'confirm': 'Confirm',
      'confirm_password': 'Confirm Password',
      'confirm_payment': 'CONFIRM PAYMENT',
      'connection_too_slow': 'Connection too slow',
      'contact_support': 'CONTACT SUPPORT',
      'copyright': '© 2026 Kouture Marketplace. All rights reserved.',
      'costumes': 'Suits',
      'country': 'Country',
      'country_updated': 'Country updated',
      'create_account': 'Create Account',
      'credit_card': 'Credit Card',
      'currency': 'Currency',
      'currency_updated': 'Currency updated',
      'cvv': 'CVV',
      'default': 'Default',
      'delete': 'DELETE',
      'delete_address_desc': 'Do you really want to delete this shipping address?',
      'delete_address_title': 'Delete address?',
      'delivery_estimate': 'Estimated Delivery',
      'delivery_fees': 'Delivery Fees',
      'details': 'Details',
      'discover': 'Discover',
      'do_not_close': 'Please do not close the application.',
      'edit': 'Edit',
      'edit_profile': 'Edit Profile',
      'email': 'Email',
      'email_required': 'Please enter your email',
      'enfants': 'Kids',
      'enter_opinion_hint': 'Enter your opinion here...',
      'error_fetching_products': 'Error loading recommended products.',
      'error_order_not_found': 'Error: Order not found',
      'expiry': 'Expiry',
      'explore': 'Explore',
      'explore_and_add_favorite': 'Explore our products and add your favorites!',
      'explore_products': 'Explore Products',
      'extremities': 'EXTREMITIES',
      'faq_a1': 'Go to the "Activities" tab to see the real-time tracking of your package.',
      'faq_a2': 'We accept Orange Money, MTN Mobile Money and Bank Cards (Visa/Mastercard).',
      'faq_a3': 'Yes, returns are accepted within 7 days if the item has not been worn and the security seal is intact.',
      'faq_a4': 'Most of our designers tailor your outfits in 5 to 10 business days.',
      'faq_q1': 'How to track my order?',
      'faq_q2': 'What are the payment methods?',
      'faq_q3': 'Can I return an item?',
      'faq_q4': 'Tailoring times?',
      'favorites': 'Favorites',
      'favorites_tailors': 'My Favorite Tailors',
      'female': 'Female',
      'field_required': 'This field is required',
      'filters': 'Filters',
      'finish': 'FINISH',
      'follow_tailors_subtext': 'Follow your favorite tailors to find them here!',
      'followers': 'Followers',
      'forgot_password': 'Forgot Password?',
      'full_name': 'Full Name',
      'full_name_hint': 'e.g. John Doe',
      'gender': 'Gender',
      'general_notifications': 'General Notifications',
      'help_expert_title': 'Need to talk to an expert?',
      'help_main_question': 'How can we help you?',
      'help_support': 'Help & Support',
      'helpful': 'helpful',
      'hips': 'Hips',
      'home': 'Home',
      'inseam': 'Inseam',
      'instructions': 'Instructions',
      'invalid_email': 'Invalid email',
      'invalid_number': 'Invalid number',
      'invoice_title': 'Invoice for order',
      'is_helpful_q': 'Helpful?',
      'jan': 'Jan',
      'jul': 'Jul',
      'just_now': 'Just now',
      'kids': 'Kids',
      'language': 'Language',
      'last_update': 'Last updated',
      'legs': 'LEGS',
      'loading': 'Loading...',
      'loading_african_countries': 'Loading African countries...',
      'loading_error': 'Unable to load the country list. Check your connection.',
      'loading_products': 'Loading products...',
      'login': 'Login',
      'login_now': 'Login Now',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'male': 'Male',
      'mark_all_read': 'Mark all read',
      'marketplace_updates': 'Marketplace Updates',
      'measurements_saved': 'Measurements saved successfully!',
      'measurements_title': 'MEASUREMENTS',
      'men': 'Men',
      'messages': 'Messages',
      'momo_desc': 'Enter your MTN Mobile Money number to initiate the payment.',
      'morphology': 'MORPHOLOGY',
      'my_addresses': 'My Addresses',
      'my_items': 'My Items',
      'my_measurements': 'My Measurements',
      'my_profile': 'My Profile',
      'name_required': 'Please enter your name',
      'native_currency_suggestion': 'Suggested for your country',
      'neck': 'Neck',
      'new_address': 'New Address',
      'new_arrivals': 'New Arrivals',
      'new_collections': 'New Collections',
      'new_collections_desc': 'Notify when new products arrive',
      'next': 'NEXT',
      'no': 'NO',
      'no_addresses': 'No addresses saved',
      'no_country_found': 'No country found',
      'no_favorite_products': 'No favorite products yet.',
      'no_favorite_tailors': 'No favorite tailors yet.',
      'no_messages': 'No messages yet',
      'no_notifications': 'No notifications yet',
      'no_orders': 'No orders yet',
      'no_products': 'No products',
      'no_products_found': 'No products found in this category.',
      'no_results': 'No results found.',
      'no_reviews': 'No reviews yet',
      'no_reviews_filter': 'No reviews for this filter yet',
      'notification_blocked': 'Notification blocked by settings.',
      'notification_empty_desc': 'We will notify you when something important arrives.',
      'notification_sent': 'Notification sent!',
      'notification_settings': 'Notification Settings',
      'notifications': 'Notifications',
      'official_shop': 'Official Shop',
      'onb_desc_1': 'Discover the excellence of local craftsmanship. Our artisans transform the finest fabrics into unique masterpieces.',
      'onb_desc_2': 'Every stitch tells a story. Access the superior quality of authentically African custom tailoring.',
      'onb_desc_3': 'Wear your culture with pride. A modern and perfect cut, designed to enhance your silhouette and heritage.',
      'onb_tag_1': 'KNOW-HOW',
      'onb_tag_2': 'ART & PASSION',
      'onb_tag_3': 'PERFECT CUTS',
      'onb_title_1': 'Artisan Heritage',
      'onb_title_2': 'Precision & Passion',
      'onb_title_3': 'Elegant Africa',
      'online': 'Online',
      'optional': '(Optional)',
      'orange_money_desc': 'Enter your Orange Money number to initiate the payment.',
      'order': 'Order',
      'order_activity': 'Order Activity',
      'order_confirmed': 'Order Confirmed',
      'order_details': 'VIEW DETAILS',
      'order_no': 'Order No.',
      'order_receipt': 'Your Receipt',
      'order_status': 'Order Status',
      'order_status_desc': 'Real-time tracking notifications',
      'order_success': 'Order Successful!',
      'order_success_desc': 'Your order has been recorded successfully. You will receive a notification very soon.',
      'order_summary': 'Order Summary',
      'orders': 'Orders',
      'other': 'Other',
      'password': 'Password',
      'pay': 'Pay',
      'pay_now': 'PAY NOW',
      'pay_with_momo': 'Pay with MoMo',
      'pay_with_orange_money': 'Pay with Orange Money',
      'payment_details': 'Payment Details',
      'payment_failed': 'Payment Failed',
      'payment_failed_desc': 'An error occurred while processing your transaction. Please check your balance or try a different payment method.',
      'payment_method': 'Payment Method',
      'payment_methods': 'Payment Methods',
      'personal': 'Personal',
      'personal_info': 'Personal Information',
      'phone_hint': 'e.g. +237 600 000 000',
      'phone_number': 'Phone number',
      'phone_number_hint': 'e.g.: 690 00 00 00',
      'phone_required': 'Please enter a number',
      'popular_tags': 'Popular Tags',
      'price_alerts': 'Price Alerts',
      'price_alerts_desc': 'Notify about price drops',
      'price_range': 'Price Range',
      'privacy_footer': 'For any questions, contact our data protection officer via the Help menu.',
      'privacy_policy': 'Privacy Policy',
      'privacy_section1_content': 'Kouture collects information to improve your experience: name, email, order history and style preferences.',
      'privacy_section1_title': '1. Data Collection',
      'privacy_section2_content': 'Your data is used to personalize your recommendations, process your orders and inform you of promotions.',
      'privacy_section2_title': '2. Data Usage',
      'privacy_section3_content': 'We use state-of-the-art security protocols to protect your personal information and banking transactions.',
      'privacy_section3_title': '3. Security',
      'privacy_section4_content': 'You have the right to access, rectify and delete your personal data at any time.',
      'privacy_section4_title': '4. Your Rights',
      'product_details': 'Product Details',
      'products': 'Products',
      'products_found': 'products',
      'profile': 'Profile',
      'profile_updated': 'Profile updated successfully!',
      'progressions': 'Progressions',
      'promotions_desc': 'Daily coupons and offers',
      'push_notifications': 'Push Notifications',
      'push_notifications_desc': 'Enable or disable push alerts',
      'qty_label': 'Qty',
      'quantity': 'Qty',
      'rating_label': 'Rating',
      'recent_searches': 'Recent Searches',
      'recommended_tailors': 'Recommended Tailors',
      'region_hint': 'e.g. Center',
      'register': 'Sign Up',
      'register_now': 'Register Now',
      'required_field': 'Required field',
      'reset': 'Reset',
      'results_for': 'Results for',
      'retry': 'Retry',
      'return_home': 'RETURN HOME',
      'review_submitted': 'Your review has been submitted successfully.',
      'reviews': 'Reviews',
      'robes': 'Dresses',
      'sacs': 'Bags',
      'sales': 'Sales',
      'save': 'Save',
      'save_address': 'SAVE ADDRESS',
      'save_changes': 'Save Changes',
      'saved_payment_methods': 'Saved Payment Methods Configuration',
      'search_country': 'Search country...',
      'search_country_hint': 'Search for a country...',
      'search_hint': 'Search on Kouture...',
      'search_language': 'Search language...',
      'search_products_hint': 'Search for a product...',
      'secure_processing': 'Secure processing...',
      'see_all': 'See All',
      'see_reviews': 'See Reviews',
      'select': 'Select',
      'select_color': 'Select Color',
      'select_country': 'Select Country',
      'select_currency': 'Select currency',
      'select_language': 'Select Language',
      'select_quantity': 'Select Quantity',
      'select_rating_error': 'Please select a rating',
      'select_size': 'Select Size',
      'send_email': 'SEND EMAIL',
      'set_as_default': 'Set as default',
      'set_as_default_desc': 'Automatically used during checkout',
      'settings': 'Settings',
      'shipping': 'Shipping',
      'shipping_address': 'Shipping Address',
      'shipping_addresses': 'Shipping Addresses',
      'shop': 'Shop',
      'shop_now': 'SHOP NOW',
      'shoulder': 'Shoulder',
      'similar_products': 'Similar Products',
      'simulate_push': 'SIMULATE PUSH',
      'size': 'Size',
      'size_label': 'Size',
      'skip': 'SKIP',
      'sound': 'Sound',
      'sound_desc': 'Play sound on discovery',
      'specifications': 'Specifications',
      'star': 'star',
      'stars': 'stars',
      'start': 'START',
      'start_searching': 'Start searching...',
      'statistics': 'Statistics',
      'status': 'Status',
      'status_accepted': 'Accepted',
      'status_accepted_desc': 'The tailor has accepted your order',
      'status_confection': 'In Confection',
      'status_confection_desc': 'Your outfit is being sewn',
      'status_delivered': 'Delivered',
      'status_delivered_desc': 'You have received your package',
      'status_pending': 'Pending',
      'status_placed': 'Order Placed',
      'status_placed_desc': 'Your order has been received',
      'status_shipped': 'Shipped',
      'status_shipped_desc': 'The package is on its way to you',
      'street_address': 'Street Address',
      'street_hint': 'e.g. Peace Street, Bastos',
      'streetwear': 'Streetwear',
      'submit_review': 'SUBMIT REVIEW',
      'subtotal': 'Sub-total',
      'suggested_for_country': 'Suggested for your country',
      'summary': 'Summary',
      'tailors': 'Tailors',
      'terms_conditions': 'Terms and Conditions',
      'thank_you': 'Thank You!',
      'thigh': 'Thigh',
      'top_trends': 'Top Trends',
      'total': 'TOTAL',
      'total_items': 'Total Items',
      'total_paid': 'Total Paid',
      'track_order': 'TRACK ORDER',
      'traditionnel': 'Traditional',
      'try_other_keywords': 'Try other keywords or tags.',
      'type_message_hint': 'Type a message...',
      'update_success': 'Successfully updated',
      'updated_on': 'Updated on',
      'vendor': 'Vendor',
      'verification_sent': 'We have sent a verification code to you.',
      'verify_notifications': 'Use this button to verify if the notifications appear based on your current switch settings.',
      'version': 'Version',
      'vibrate': 'Vibrate',
      'vibrate_desc': 'Vibrate on notification arrival',
      'view_all': 'View All',
      'view_my_order': 'VIEW MY ORDER',
      'view_products': 'VIEW PRODUCTS',
      'visit': 'Visit',
      'waist': 'Waist',
      'welcome_back': 'Welcome Back',
      'what_is_rate': 'What is your rate?',
      'women': 'Women',
      'work': 'Work',
      'wrist': 'Wrist',
      'write_opinion': 'Please write your opinion',
      'write_review': 'WRITE A REVIEW',
      'yes': 'YES',
      'your_current_country': 'Your current country',
    },
    'Français': {
      'about': 'À propos',
      'about_kouture': 'À propos de Kouture',
      'accessoires': 'Accessoires',
      'accessories': 'Accessoires',
      'account': 'Compte',
      'account_created': 'Compte Créé !',
      'activities': 'Activités',
      'add_address_desc': 'Ajoutez une adresse pour faciliter vos commandes.',
      'add_new_address': 'AJOUTER UNE NOUVELLE ADRESSE',
      'add_payment_method': 'Ajouter un mode de paiement',
      'add_photo': 'Ajouter une photo',
      'add_review': 'Ajouter un avis',
      'add_to_cart': 'Ajouter au panier',
      'added_to_cart': 'Ajouté au panier !',
      'address_added_success': 'Adresse ajoutée avec succès',
      'all': 'Tous',
      'all_currencies': 'Toutes les devises',
      'already_have_account': 'Déjà un compte ?',
      'ankle': 'Cheville',
      'apply_filters': 'Appliquer les filtres',
      'arm_length': 'Longueur du bras',
      'articles': 'article(s)',
      'at': 'à',
      'back': 'RETOUR',
      'bank_card': 'Carte Bancaire',
      'bank_card_title': 'Carte Bancaire',
      'biceps': 'Biceps',
      'birth_date': 'Date de naissance',
      'bust_chest': 'Poitrine',
      'buy_now': 'Acheter maintenant',
      'calf': 'Mollet',
      'cancel': 'Annuler',
      'card_name': 'Nom sur la carte',
      'card_number': 'Numéro de carte',
      'cardholder': 'TITULAIRE',
      'cart': 'Mon Panier',
      'cart_empty': 'Votre panier est vide',
      'categories': 'Catégories',
      'categories_title': 'Catégories',
      'chaussures': 'Chaussures',
      'checkout': 'Passer au paiement',
      'checkout_confirmation': 'Confirmation de paiement',
      'city': 'Ville',
      'city_hint': 'ex: Yaoundé',
      'clear_all': 'Tout effacer',
      'colors': 'Couleurs',
      'confirm': 'Confirmer',
      'confirm_password': 'Confirmer le mot de passe',
      'confirm_payment': 'CONFIRMER LE PAIEMENT',
      'connection_too_slow': 'Connexion trop lente',
      'contact_support': 'CONTACTER LE SUPPORT',
      'copyright': '© 2026 Kouture Marketplace. Tous droits réservés.',
      'costumes': 'Costumes',
      'country': 'Pays',
      'country_updated': 'Pays mis à jour',
      'create_account': 'Créer un compte',
      'credit_card': 'Carte bancaire',
      'currency': 'Devise',
      'currency_updated': 'Devise mise à jour',
      'cvv': 'CVV',
      'default': 'Défaut',
      'delete': 'SUPPRIMER',
      'delete_address_desc': 'Voulez-vous vraiment supprimer cette adresse de livraison ?',
      'delivery_estimate': 'Livraison Estimée',
      'delivery_fees': 'Frais de livraison',
      'details': 'Détails',
      'discover': 'Découvrir',
      'edit': 'Modifier',
      'edit_profile': 'Modifier le profil',
      'email': 'Email',
      'email_required': 'Veuillez entrer votre email',
      'enfants': 'Enfants',
      'enter_opinion_hint': 'Entrez votre avis ici...',
      'error_fetching_products': 'Erreur lors de la récupération des produits recommandés.',
      'error_order_not_found': 'Erreur : Commande introuvable',
      'expiry': 'Expiration',
      'explore': 'Explorer',
      'explore_and_add_favorite': 'Explorez nos produits et ajoutez vos favoris !',
      'explore_products': 'Explorer les produits',
      'extremities': 'EXTRÉMITÉS',
      'faq_a2': 'Nous acceptons Orange Money, MTN Mobile Money et les Cartes Bancaires (Visa/Mastercard).',
      'faq_a4': 'La plupart de nos créateurs confectionnent vos tenues en 5 à 10 jours ouvrés.',
      'faq_q1': 'Comment suivre ma commande ?',
      'faq_q2': 'Quels sont les modes de paiement ?',
      'faq_q3': 'Puis-je retourner un article ?',
      'faq_q4': 'Délais de confection ?',
      'favorites': 'Favoris',
      'favorites_tailors': 'Mes Couturiers Favoris',
      'female': 'Femme',
      'field_required': 'Ce champ est requis',
      'filters': 'Filtres',
      'finish': 'TERMINER',
      'follow_tailors_subtext': 'Suivez vos couturiers préférés pour les retrouver ici !',
      'followers': 'Abonnés',
      'forgot_password': 'Mot de passe oublié ?',
      'full_name': 'Nom complet',
      'full_name_hint': 'ex: Jean Dupont',
      'gender': 'Genre',
      'general_notifications': 'Notifications Générales',
      'help_expert_title': 'Besoin de parler à un expert ?',
      'help_main_question': 'Comment pouvons-nous vous aider ?',
      'help_support': 'Aide & Support',
      'helpful': 'utile',
      'hips': 'Hanches',
      'home': 'Maison',
      'inseam': 'Entrejambe',
      'instructions': 'Instructions',
      'invalid_email': 'Email invalide',
      'invalid_number': 'Numéro invalide',
      'invoice_title': 'Facture commande',
      'is_helpful_q': 'Utile ?',
      'jan': 'Jan',
      'jul': 'Juil',
      'kids': 'Enfants',
      'language': 'Langue',
      'last_update': 'Dernière mise à jour',
      'legs': 'JAMBES',
      'loading': 'Chargement...',
      'loading_african_countries': 'Chargement des pays africains...',
      'loading_error': 'Impossible de charger la liste des pays. Vérifiez votre connexion.',
      'loading_products': 'Chargement des produits...',
      'login': 'Connexion',
      'login_now': 'Connectez-vous',
      'logout': 'Déconnexion',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'male': 'Homme',
      'mark_all_read': 'Tout marquer comme lu',
      'marketplace_updates': 'Mises à jour du Marché',
      'measurements_saved': 'Mensurations enregistrées avec succès !',
      'measurements_title': 'MENSURATIONS',
      'men': 'Hommes',
      'messages': 'Messages',
      'momo_desc': 'Entrez votre numéro MTN Mobile Money pour initier le paiement.',
      'momo_instructions': '1. Validez la transaction sur votre téléphone.\n2. Composez le *126# si vous ne recevez pas de notification.\n3. Entrez votre code PIN pour confirmer.',
      'morphology': 'MORPHOLOGIE',
      'my_addresses': 'Mes Adresses',
      'my_items': 'Mes articles',
      'my_measurements': 'Mes Mensurations',
      'my_profile': 'Mon Profil',
      'name_required': 'Veuillez entrer votre nom',
      'native_currency_suggestion': 'Suggérée pour votre pays',
      'neck': 'Cou',
      'new_address': 'Nouvelle Adresse',
      'new_arrivals': 'Nouveautés',
      'new_collections': 'Nouvelles Collections',
      'next': 'SUIVANT',
      'no': 'NON',
      'no_addresses': 'Aucune adresse enregistrée',
      'no_country_found': 'Aucun pays trouvé',
      'no_favorite_products': 'Aucun produit favori.',
      'no_favorite_tailors': 'Aucun couturier favori.',
      'no_messages': 'Pas encore de messages',
      'no_notifications': 'Pas encore de notifications',
      'no_orders': 'Aucune commande',
      'no_products': 'Aucun produit',
      'no_products_found': 'Aucun produit trouvé dans cette catégorie.',
      'no_results': 'Aucun résultat trouvé.',
      'no_reviews': 'Aucun avis pour le moment',
      'no_reviews_filter': 'Aucun avis pour ce filtre',
      'notification_blocked': 'Notification bloquée par les paramètres.',
      'notification_sent': 'Notification envoyée !',
      'notification_settings': 'Notifications',
      'notifications': 'Notifications',
      'official_shop': 'Boutique officielle',
      'onb_desc_2': 'Chaque point raconte une histoire. Accédez à la qualité supérieure du sur-mesure authentiquement africain.',
      'onb_desc_3': 'Portez votre culture avec fierté. Une coupe moderne et parfaite, conçue pour valoriser votre silhouette et votre héritage.',
      'onb_tag_1': 'SAVOIR FAIRE',
      'onb_tag_2': 'ART ET PASSION',
      'onb_tag_3': 'COUPES PARFAITES',
      'onb_title_1': 'Héritage Artisanal',
      'onb_title_2': 'Précision & Passion',
      'onb_title_3': 'Afrique Élégante',
      'online': 'En ligne',
      'optional': '(Optionnel)',
      'orange_money_desc': 'Entrez votre numéro Orange Money pour initier le paiement.',
      'orange_money_instructions': '1. Validez la transaction sur votre téléphone.\n2. Composez le #150*50# si vous ne recevez pas de notification.\n3. Entrez votre code PIN pour confirmer.',
      'order': 'Commande',
      'order_activity': 'Activité des Commandes',
      'order_confirmed': 'Commande Confirmée',
      'order_details': 'VOIR DÉTAILS',
      'order_no': 'Commande No.',
      'order_receipt': 'Votre Reçu',
      'order_status': 'Statut de la Commande',
      'order_status_desc': 'Notifications de suivi en temps réel',
      'order_success': 'Commande Réussie !',
      'order_success_desc': 'Votre commande a été enregistrée avec succès. Vous recevrez une notification très bientôt.',
      'order_summary': 'Récapitulatif',
      'orders': 'Commandes',
      'other': 'Autre',
      'password': 'Mot de passe',
      'pay': 'Payer',
      'pay_now': 'PAYER MAINTENANT',
      'pay_with_momo': 'Payer avec MoMo',
      'pay_with_orange_money': 'Payer avec Orange Money',
      'payment_details': 'Détails du paiement',
      'payment_failed': 'Échec du Paiement',
      'payment_failed_desc': 'Une erreur est survenue lors du traitement de votre transaction. Veuillez vérifier votre solde ou essayer un autre moyen de paiement.',
      'payment_method': 'Moyen de paiement',
      'payment_methods': 'Modes de paiement',
      'personal': 'Personnel',
      'personal_info': 'Informations personnelles',
      'phone_hint': 'ex: +237 600 000 000',
      'phone_number': 'Numéro de téléphone',
      'phone_number_hint': 'ex: 690 00 00 00',
      'phone_required': 'Veuillez entrer un numéro',
      'popular_tags': 'Tags populaires',
      'price_alerts': 'Alertes de Prix',
      'price_alerts_desc': 'Prévenir des baisses de prix',
      'price_range': 'Tranche de prix',
      'privacy_footer': 'Pour toute question, contactez notre délégué à la protection des données via le menu Aide.',
      'privacy_policy': 'Politique de Confidentialité',
      'privacy_section1_content': 'Kouture collecte des informations pour améliorer votre expérience : nom, email, historique de commandes et préférences de style.',
      'privacy_section1_title': '1. Collecte des données',
      'privacy_section2_content': 'Vos données sont utilisées pour personnaliser vos recommandations, traiter vos commandes et vous informer des promotions.',
      'privacy_section2_title': '2. Utilisation des données',
      'privacy_section3_content': 'Nous utilisons des protocoles de sécurité de pointe pour protéger vos informations personnelles et transactions bancaires.',
      'privacy_section3_title': '3. Sécurité',
      'privacy_section4_title': '4. Vos droits',
      'product_details': 'Détails du produit',
      'products': 'Produits',
      'products_found': 'produits',
      'profile': 'Profil',
      'profile_updated': 'Profil mis à jour avec succès !',
      'progressions': 'Progressions',
      'promotions_desc': 'Coupons et offres quotidiennes',
      'push_notifications': 'Notifications Push',
      'push_notifications_desc': 'Activer ou désactiver les alertes push',
      'qty_label': 'Qté',
      'quantity': 'Qté',
      'rating_label': 'Note',
      'recent_searches': 'Recherches récentes',
      'recommended_tailors': 'Tailleurs recommandés',
      'region_hint': 'ex: Centre',
      'register': 'Inscription',
      'register_now': 'Inscrivez-vous',
      'required_field': 'Champ requis',
      'reset': 'Réinitialiser',
      'results_for': 'Résultats pour',
      'retry': 'Réessayer',
      'review_submitted': 'Votre avis a été soumis avec succès.',
      'reviews': 'Avis',
      'robes': 'Robes',
      'sacs': 'Sacs',
      'sales': 'Ventes',
      'save': 'Enregistrer',
      'save_changes': 'Sauvegarder les modifications',
      'saved_payment_methods': 'Configuration des modes de paiement enregistrés',
      'search_country': 'Rechercher un pays...',
      'search_country_hint': 'Rechercher un pays...',
      'search_hint': 'Rechercher sur Kouture...',
      'search_language': 'Rechercher une langue...',
      'search_products_hint': 'Rechercher un produit...',
      'secure_processing': 'Traitement sécurisé...',
      'see_all': 'Tout voir',
      'see_reviews': 'Voir les avis',
      'select': 'Sélectionner',
      'select_color': 'Choisir la couleur',
      'select_country': 'Sélectionner le pays',
      'select_currency': 'Sélectionner la devise',
      'select_language': 'Sélectionner la langue',
      'select_quantity': 'Choisir la quantité',
      'select_rating_error': 'Veuillez sélectionner une note',
      'select_size': 'Choisir la taille',
      'send_email': 'ENVOYER UN EMAIL',
      'set_as_default': 'Définir par défaut',
      'set_as_default_desc': 'Utilisée automatiquement lors du paiement',
      'settings': 'Paramètres',
      'shipping': 'Livraison',
      'shipping_address': 'Adresse de livraison',
      'shipping_addresses': 'Adresses de Livraison',
      'shop': 'Boutique',
      'shop_now': 'ACHETER MAINTENANT',
      'shoulder': 'Épaule',
      'similar_products': 'Produits similaires',
      'simulate_push': 'SIMULER PUSH',
      'size': 'Taille',
      'size_label': 'Taille',
      'skip': 'PASSER',
      'sound': 'Son',
      'sound_desc': 'Jouer un son à la réception',
      'specifications': 'Spécifications',
      'star': 'étoile',
      'stars': 'étoiles',
      'start': 'COMMENCER',
      'start_searching': 'Commencez à chercher...',
      'statistics': 'Statistiques',
      'status': 'Statut',
      'status_accepted': 'Acceptée',
      'status_accepted_desc': 'Le couturier a accepté votre commande',
      'status_confection': 'En confection',
      'status_delivered': 'Livrée',
      'status_delivered_desc': 'Vous avez reçu votre colis',
      'status_pending': 'En attente',
      'status_placed': 'Commande placée',
      'status_placed_desc': 'Votre commande a été reçue',
      'status_shipped': 'Expédiée',
      'status_shipped_desc': 'Le colis est en route vers vous',
      'street_address': 'Adresse / Rue',
      'street_hint': 'ex: Rue de la Paix, Bastos',
      'streetwear': 'Streetwear',
      'subtotal': 'Sous-total',
      'suggested_for_country': 'Suggérée pour votre pays',
      'summary': 'Résumé',
      'tailors': 'Couturiers',
      'terms_conditions': 'Termes et Conditions',
      'thank_you': 'Merci !',
      'thigh': 'Cuisse',
      'top_trends': 'Top Tendances',
      'total': 'TOTAL',
      'total_items': 'Total Articles',
      'total_paid': 'Total Payé',
      'track_order': 'SUIVRE LE COLIS',
      'traditionnel': 'Traditionnel',
      'type_message_hint': 'Écrire un message...',
      'update_success': 'Mise à jour réussie',
      'updated_on': 'Mis à jour le',
      'vendor': 'Vendeur',
      'verification_sent': 'Nous vous avons envoyé un code de vérification.',
      'verify_notifications': 'Utilisez ce bouton pour vérifier si les notifications apparaissent avec vos paramètres.',
      'version': 'Version',
      'vibrate': 'Vibreur',
      'view_all': 'Voir tout',
      'view_my_order': 'VOIR MA COMMANDE',
      'view_products': 'VOIR LES PRODUITS',
      'visit': 'Visiter',
      'waist': 'Taille',
      'welcome_back': 'Bon retour',
      'what_is_rate': 'Quelle est votre note ?',
      'women': 'Femmes',
      'work': 'Bureau',
      'wrist': 'Poignet',
      'write_opinion': 'Veuillez écrire votre avis',
      'write_review': 'ÉCRIRE UN AVIS',
      'yes': 'OUI',
      'your_current_country': 'Votre pays actuel',
    },
    'Español': {
      'settings': 'Ajustes',
      'personal': 'Personal',
      'my_profile': 'Mi Perfil',
      'my_measurements': 'Mis Medidas',
      'shipping_addresses': 'Direcciones de Envío',
      'favorites': 'Favoritos',
      'notification_settings': 'Notificaciones',
      'shop': 'Tienda',
      'country': 'País',
      'currency': 'Moneda',
      'terms_conditions': 'Términos y Condiciones',
      'account': 'Cuenta',
      'language': 'Idioma',
      'help_support': 'Ayuda y Soporte',
      'about_kouture': 'Sobre Kouture',
      'version': 'Versión',
      'select_language': 'Seleccionar idioma',
      'select_country': 'Seleccionar país',
      'select_currency': 'Seleccionar moneda',
      'search_language': 'Buscar idioma...',
      'search_country': 'Buscar país...',
      'loading': 'Cargando...',
      'retry': 'Reintentar',
      'update_success': 'Actualizado con éxito',
      'native_currency_suggestion': 'Sugerido para su país',
      'all_currencies': 'Todas las monedas',
      // Auth
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'forgot_password': '¿Olvidó su contraseña?',
      'dont_have_account': '¿No tiene una cuenta?',
      'already_have_account': '¿Ya tiene una cuenta?',
      'login_now': 'Inicie sesión ahora',
      'register_now': 'Regístrese ahora',
      'welcome_back': 'Bienvenido de nuevo',
      'create_account': 'Crear una cuenta',
      // Home & Nav
      'home': 'Inicio',
      'discover': 'Descubrir',
      'activities': 'Actividades',
      'profile': 'Perfil',
      'top_trends': 'Tendencias actuales',
      'explore': 'Explorar',
      'see_all': 'Ver todo',
      'search_hint': 'Buscar en Kouture...',
      // Profile
      'followers': 'Seguidores',
      'orders': 'Pedidos',
      'edit_profile': 'Editar Perfil',
      'logout': 'Cerrar sesión',
      // Miscellaneous
      'skip': 'SALTAR',
      'start': 'COMENZAR',
      'confirm_password': 'Confirmar contraseña',
      'full_name': 'Nombre completo',
      'agree_terms': 'Acepto los Términos y Condiciones',
      'account_created': '¡Cuenta creada!',
      'verification_sent': 'Le hemos enviado un código de verificación.',
      'new_arrivals': 'Novedades',
      'categories': 'Categorías',
      'men': 'Hombres',
      'women': 'Mujeres',
      'kids': 'Niños',
      'accessories': 'Accesorios',
      'recommended_tailors': 'Sastres recomendados',
      'shop_now': 'COMPRAR AHORA',
      'personal_info': 'Información personal',
      'city': 'Ciudad',
      'statistics': 'Estadísticas',
      'messages': 'Mensajes',
      'my_addresses': 'Mis Direcciones',
      'logout_confirm': '¿Está seguro de que desea cerrar la sesión?',
      'yes': 'SÍ',
      'no': 'NO',
      'no_messages': 'Aún no hay mensajes',
      'no_orders': 'Aún no hay pedidos',
      'articles': 'artículo(s)',
      'total': 'TOTAL',
      'details': 'Detalles',
      'cart': 'Mi Carrito',
      'cart_empty': 'Tu carrito está vacío',
      'subtotal': 'Subtotal',
      'shipping': 'Envío',
      'checkout': 'Pasar por caja',
      'checkout_confirmation': 'Confirmación de pago',
      'shipping_address': 'Dirección de envío',
      'payment_method': 'Método de pago',
      'payment_details': 'Detalles del pago',
      'quantity': 'Cant.',
      'size': 'Talla',
      'edit': 'Editar',
      'credit_card': 'Tarjeta de crédito',
      'pay': 'PAGAR',
      'notifications': 'Notificaciones',
      'mark_all_read': 'Marcar todo como leído',
      'clear_all': 'Borrar todo',
      'no_notifications': 'Aún no hay notificaciones',
      'notification_empty_desc': 'Te avisaremos cuando llegue algo importante.',
      'no_results': 'No se han encontrado resultados.',
      'start_searching': 'Empieza a buscar...',
      'recent_searches': 'Búsquedas recientes',
      'order': 'Pedido',
      'error_order_not_found': 'Error: Pedido no encontrado',
      'summary': 'Resumen',
      'total_items': 'Total de artículos',
      'delivery_fees': 'Gastos de envío',
      'cancel': 'CANCELAR',
      'track_order': 'SEGUIR PEDIDO',
      'status': 'Estado',
      'updated_on': 'Actualizado el',
      'no_addresses': 'No hay direcciones guardadas',
      'add_address_desc': 'Añade una dirección para facilitar tus pedidos.',
      'default': 'Predeterminado',
      'set_as_default': 'Establecer como predeterminada',
      'add_new_address': 'AÑADIR NUEVA DIRECCIÓN',
      'delete_address_title': '¿Eliminar dirección?',
      'delete_address_desc': '¿Realmente quieres eliminar esta dirección de envío?',
      'delete': 'ELIMINAR',
      'home': 'Casa',
      'work': 'Trabajo',
      'new_address': 'Nueva dirección',
      'address_type': 'Tipo de dirección',
      'other': 'Otro',
      'full_name': 'Nombre completo',
      'full_name_hint': 'ej: Juan Pérez',
      'phone_hint': 'ej: +237 600 000 000',
      'street_address': 'Dirección / Calle',
      'street_hint': 'ej: Calle de la Paz, Bastos',
      'city_hint': 'ej: Yaoundé',
      'region_hint': 'ej: Centro',
      'set_as_default_desc': 'Utilizada automáticamente al pagar',
      'save_address': 'GUARDAR DIRECCIÓN',
      'address_added_success': 'Dirección añadida con éxito',
      'field_required': 'Este campo es obligatorio',
      'online': 'En línea',
      'type_message_hint': 'Escribe un mensaje...',
      'order_no': 'Pedido No.',
      'progressions': 'Progresos',
      'status_placed': 'Pedido realizado',
      'status_placed_desc': 'Su pedido ha sido recibido',
      'status_accepted': 'Aceptado',
      'status_accepted_desc': 'El sastre ha aceptado su pedido',
      'status_confection': 'En confección',
      'status_confection_desc': 'Su traje está siendo cosido',
      'status_shipped': 'Enviado',
      'status_shipped_desc': 'El paquete está en camino',
      'status_delivered': 'Entregado',
      'status_delivered_desc': 'Usted ha recibido su paquete',
      'filters': 'Filtros',
      'reset': 'Restablecer',
      'price_range': 'Rango de precios',
      'apply_filters': 'Aplicar filtros',
      'colors': 'Colores',
      'reviews': 'Reseñas',
      'write_review': 'ESCRIBIR UNA RESEÑA',
      'helpful': 'útil',
      'is_helpful_q': '¿Es útil?',
      'no_reviews': 'No hay reseñas todavía',
      'no_reviews_filter': 'No hay reseñas para este filtro',
      'all': 'Todos',
      'stars': 'estrellas',
      'star': 'estrella',
      'just_now': 'Ahora mismo',
      'add_review': 'Añadir reseña',
      'what_is_rate': '¿Cuál es tu calificación?',
      'select_rating_error': 'Por favor, selecciona una calificación',
      'write_opinion': 'Por favor, escribe tu opinión',
      'enter_opinion_hint': 'Escribe tu opinión aquí...',
      'add_photo': 'Añadir foto',
      'optional': '(Opcional)',
      'thank_you': '¡Gracias!',
      'review_submitted': 'Tu reseña ha sido enviada con éxito.',
      'submit_review': 'ENVIAR RESEÑA',
      'order_summary': 'Resumen del pedido',
      'cart_empty': 'Tu carrito está vacío',
      'explore_products': 'Explorar productos',
      'my_items': 'Mis artículos',
      'size_label': 'Talla',
      'qty_label': 'Cant',
      'bank_card': 'Tarjeta Bancaria',
      'pay': 'Pagar',
      'see_reviews': 'Ver reseñas',
      'official_shop': 'Tienda oficial',
      'visit': 'Visitar',
      'select_quantity': 'Seleccionar cantidad',
      'select_size': 'Seleccionar talla',
      'select_color': 'Seleccionar color',
      'add_to_cart': 'Añadir al carrito',
      'buy_now': 'Comprar ahora',
      'product_details': 'Detalles del producto',
      'specifications': 'Especificaciones',
      'view_all': 'Ver todo',
      'similar_products': 'Productos similares',
      'added_to_cart': '¡Añadido al carrito!',
      'edit_profile': 'Editar perfil',
      'save': 'Guardar',
      'profile_updated': '¡Perfil actualizado con éxito!',
      'full_name': 'Nombre completo',
      'gender': 'Género',
      'birth_date': 'Fecha de nacimiento',
      'name_required': 'Por favor, introduce tu nombre',
      'email_required': 'Por favor, introduce tu email',
      'invalid_email': 'Email inválido',
      'phone_required': 'Por favor, introduce tu teléfono',
      'male': 'Hombre',
      'female': 'Mujer',
      'other': 'Otro',
      'select': 'Seleccionar',
      'save_changes': 'Guardar cambios',
      'measurements_title': 'MEDIDAS',
      'morphology': 'MORFOLOGÍA',
      'extremities': 'EXTREMIDADES',
      'legs': 'PIERNAS',
      'neck': 'Cuello',
      'shoulder': 'Hombros',
      'bust_chest': 'Pecho',
      'waist': 'Cintura',
      'hips': 'Caderas',
      'arm_length': 'Brazo',
      'biceps': 'Bíceps',
      'wrist': 'Muñeca',
      'inseam': 'Entrepierna',
      'thigh': 'Muslo',
      'calf': 'Pantorrilla',
      'ankle': 'Tobillo',
      'measurements_saved': 'Medidas guardadas con éxito',
      'finish': 'TERMINAR',
      'about_desc': 'Kouture es el destino definitivo para la moda africana de alta gama. Conectamos a los mejores artesanos y diseñadores con una audiencia global, con énfasis en la calidad y el hecho a medida.',
      'copyright': '© 2026 Kouture Marketplace. Todos los derechos reservados.',
      'privacy_policy': 'Política de Privacidad',
      'last_update': 'Última actualización',
      'privacy_section1_title': '1. Recopilación de datos',
      'privacy_section1_content': 'Kouture recopila información para mejorar su experiencia: nombre, correo electrónico, historial de pedidos y preferencias de estilo.',
      'privacy_section2_title': '2. Uso de datos',
      'privacy_section2_content': 'Sus datos se utilizan para personalizar sus recomendaciones, procesar sus pedidos e informarle sobre promociones.',
      'privacy_section3_title': '3. Seguridad',
      'privacy_section3_content': 'Utilizamos protocolos de seguridad de vanguardia para proteger su información personal y transacciones bancarias.',
      'privacy_section4_title': '4. Sus derechos',
      'privacy_section4_content': 'Tiene derecho a acceder, rectificar y eliminar sus datos personales en cualquier momento.',
      'privacy_footer': 'Si tiene alguna pregunta, comuníquese con nuestro oficial de protección de datos a través del menú de Ayuda.',
      'help_main_question': '¿Cómo podemos ayudarte?',
      'faq_q1': '¿Cómo rastrear mi pedido?',
      'faq_a1': 'Vaya a la pestaña "Actividades" para ver el seguimiento en tiempo real de su paquete.',
      'faq_q2': '¿Cuáles son los métodos de pago?',
      'faq_a2': 'Aceptamos Orange Money, MTN Mobile Money y Tarjetas Bancarias (Visa/Mastercard).',
      'faq_q3': '¿Puedo devolver un artículo?',
      'faq_a3': 'Sí, se aceptan devoluciones dentro de los 7 días si el artículo no ha sido usado y el sello de seguridad está intacto.',
      'faq_q4': '¿Tiempos de confección?',
      'faq_a4': 'La mayoría de nuestros diseñadores confeccionan sus trajes en 5 a 10 días hábiles.',
      'help_expert_title': '¿Necesitas hablar con un experto?',
      'contact_support': 'CONTACTAR AL SOPORTE',
      'send_email': 'ENVIAR UN CORREO ELECTRÓNICO',
      'jan': 'Ene', 'feb': 'Feb', 'mar': 'Mar', 'apr': 'Abr', 'may': 'May', 'jun': 'Jun',
      'jul': 'Jul', 'aug': 'Ago', 'sep': 'Sep', 'oct': 'Oct', 'nov': 'Nov', 'dec': 'Dic',
      'status_pending': 'Pendiente',
      'invoice_title': 'Factura de pedido',
      'delivery_fees': 'Gastos de envío',
      'subtotal': 'Subtotal',
      'at': 'a las',
      'popular_tags': 'Etiquetas populares',
      'search_products_hint': 'Buscar un producto...',
      'results_for': 'Resultados para',
      'no_products_found': 'Lo sentimos, no se encontraron productos.',
      'try_other_keywords': 'Intenta con otras palabras clave o etiquetas.',
      'products_found': 'productos encontrados',
      'products': 'Productos',
      'tailors': 'Sastres',
      'no_favorite_products': 'Aún no hay productos favoritos.',
      'explore_and_add_favorite': '¡Explora nuestros productos y añade tus favoritos!',
      'no_favorite_tailors': 'Aún no hay sastres favoritos.',
      'favorites_tailors': 'Mis Sastres Favoritos',
      'follow_tailors_subtext': '¡Sigue a tus sastres favoritos para encontrarlos aquí!',
      'loading_african_countries': 'Cargando países africanos...',
      'country_updated': 'País actualizado',
      'no_country_found': 'No se encontró ningún país',
      'your_current_country': 'Tu país actual',
      'search_country_hint': 'Buscar un país...',
      'retry': 'Reintentar',
      'loading_error': 'No se puede cargar la lista de países. Verifica tu conexión.',
      'connection_too_slow': 'Conexión demasiado lenta',
      'loading_products': 'Cargando productos...',
      'error_fetching_products': 'Error al cargar los productos recomendados.',
      'no_products': 'Sin productos',
      'no_recommended_products': 'No encontramos productos recomendados para ti.',
      'select_currency': 'Seleccionar moneda',
      'suggested_for_country': 'Sugerida para tu país',
      'all_currencies': 'Todas las monedas',
      'currency_updated': 'Moneda actualizada',
      'reviews': 'Reseñas',
      'view_all': 'Ver todo',
      'added_to_cart': '¡Añadido al carrito!',
      'vendor': 'Vendedor',
      'onb_title_1': 'Herencia Artesanal',
      'onb_desc_1': 'Descubre la excelencia del trabajo local. Nuestros artesanos transforman las telas más nobles en obras maestras únicas.',
      'onb_tag_1': 'SABER HACER',
      'onb_title_2': 'Precisión y Pasión',
      'onb_desc_2': 'Cada punto cuenta una historia. Accede a la calidad superior de la costura a medida auténticamente africana.',
      'onb_tag_2': 'ARTE Y PASIÓN',
      'onb_title_3': 'África Elegante',
      'onb_desc_3': 'Viste tu cultura con orgullo. Un corte moderno y perfecto, diseñado para realzar tu silueta y tu herencia.',
      'onb_tag_3': 'CORTES PERFECTOS',
      'payment_failed': 'Pago Fallido',
      'payment_failed_desc': 'Se produjo un error al procesar tu transacción. Por favor verifica tu saldo o intenta otro método de pago.',
      'order_success': '¡Pedido Exitoso!',
      'order_success_desc': 'Tu pedido ha sido registrado con éxito. Recibirás una notificación muy pronto.',
      'view_my_order': 'VER MI PEDIDO',
      'return_home': 'VOLVER AL INICIO',
      'cancel_return_home': 'CANCELAR Y VOLVER AL INICIO',
      'about': 'Sobre',
      'view_products': 'VER PRODUCTOS',
      'rating_label': 'Valoración',
      'sales': 'Ventas',
      'confirm_payment': 'CONFIRMAR PAGO',
      'pay_now': 'PAGAR AHORA',
      'instructions': 'Instrucciones',
      'pay_with_orange_money': 'Pagar con Orange Money',
      'orange_money_desc': 'Ingresa tu número de Orange Money para iniciar el pago.',
      'phone_number': 'Número de teléfono',
      'phone_number_hint': 'ej: 690 00 00 00',
      'phone_required': 'Por favor ingresa un número',
      'invalid_number': 'Número inválido',
      'orange_money_instructions': '1. Valida la transacción en tu teléfono.\n2. Marca #150*50# si no recibes una notificación.\n3. Ingresa tu PIN para confirmar.',
      'payment_methods': 'Métodos de pago',
      'add_payment_method': 'Añadir método de pago',
      'pay_with_momo': 'Pagar con MoMo',
      'momo_desc': 'Ingresa tu número de MTN Mobile Money para iniciar el pago.',
      'momo_instructions': '1. Valida la transacción en tu teléfono.\n2. Marca *126# si no recibes una notificación.\n3. Ingresa tu PIN para confirmar.',
      'bank_card_title': 'Tarjeta Bancaria',
      'card_name': 'Nombre en la tarjeta',
      'card_number': 'Número de tarjeta',
      'expiry': 'Vencimiento',
      'cvv': 'CVV',
      'required_field': 'Campo requerido',
      'cardholder': 'TITULAR',
      'secure_processing': 'Procesamiento seguro...',
      'do_not_close': 'Por favor, no cierre la aplicación.',
      'saved_payment_methods': 'Configuración de métodos de pago guardados',
      'general_notifications': 'Notificaciones Generales',
      'push_notifications': 'Notificaciones Push',
      'push_notifications_desc': 'Activar o desactivar alertas push',
      'vibrate': 'Vibrar',
      'vibrate_desc': 'Vibrar al recibir notificaciones',
      'sound': 'Sonido',
      'sound_desc': 'Reproducir sonido al descubrir',
      'marketplace_updates': 'Actualizaciones del Mercado',
      'new_collections': 'Nuevas Colecciones',
      'new_collections_desc': 'Notificar cuando lleguen nuevos productos',
      'price_alerts': 'Alertas de Precios',
      'price_alerts_desc': 'Notificar sobre bajadas de precios',
      'promotions_desc': 'Cupones y ofertas diarias',
      'order_activity': 'Actividad del Pedido',
      'order_status': 'Estado del Pedido',
      'order_status_desc': 'Notificaciones de seguimiento en tiempo real',
      'notification_sent': '¡Notificación enviada!',
      'notification_blocked': 'Notificación bloqueada por ajustes.',
      'simulate_push': 'SIMULAR PUSH',
      'verify_notifications': 'Usa este botón para verificar si aparecen las notificaciones según tu configuración.',
      'robes': 'Vestidos',
      'costumes': 'Trajes',
      'traditionnel': 'Tradicional',
      'streetwear': 'Streetwear',
      'accessoires': 'Accesorios',
      'chaussures': 'Zapatos',
      'sacs': 'Bolsos',
      'enfants': 'Niños',
      'categories_title': 'Categorías',
      'products_found': 'productos',
      'no_products_found': 'No se encontraron productos en esta categoría.',
      'order_confirmed': 'Pedido Confirmado',
      'order_receipt': 'Tu Recibo',
      'delivery_estimate': 'Entrega Estimada',
      'total_paid': 'Total Pagado',
      'order_details': 'VER DETALLES',
      'measurements_saved': '¡Medidas guardadas exitosamente!',
      'measurements_title': 'MEDIDAS',
      'morphology': 'MORFOLOGÍA',
      'extremities': 'EXTREMIDADES',
      'legs': 'PIERNAS',
      'neck': 'Cuello',
      'shoulder': 'Hombro',
      'bust_chest': 'Pecho',
      'waist': 'Cintura',
      'hips': 'Caderas',
      'arm_length': 'Longitud del brazo',
      'biceps': 'Bíceps',
      'wrist': 'Muñeca',
      'inseam': 'Entrepierna',
      'thigh': 'Muslo',
      'calf': 'Pantorrilla',
      'ankle': 'Tobillo',
      'finish': 'FINALIZAR',
      'next': 'SIGUIENTE',
      'back': 'ATRÁS',
      'confirm': 'Confirmar',
      'cancel': 'Cancelar',
    },
  };

  static String translate(String key) {
    final user = MockFirebase().currentUser;
    final lang = user?['preferences']?['language'] ?? 'Français';
    
    // Check if the specific language exists in dictionary
    if (_dictionary.containsKey(lang)) {
      return _dictionary[lang]![key] ?? _dictionary['Français']![key] ?? _dictionary['English']![key] ?? key;
    }
    
    // Fallback to French (User's request)
    return _dictionary['Français']![key] ?? _dictionary['English']![key] ?? key;
  }

  /// Returns the current language name for logic in screens (e.g. date formatting)
  static String get currentLanguage {
    final user = MockFirebase().currentUser;
    return user?['preferences']?['language'] ?? 'Français';
  }

  // Shorter alias
  static String t(String key) => translate(key);
}
